package com.cloudvault.audit;

public enum AuditAction {
    FILE_UPLOADED,
    FILE_METADATA_UPDATED,
    DOWNLOAD_LINK_CREATED,
    FILE_DELETED,
    SHARE_LINK_CREATED,
    SHARE_LINK_REVOKED,
    SHARED_FILE_ACCESSED
}
